### ISSUE TITLE
secrets.GITHUB_TOKEN

### ISSUE THREAD

**Issue by SphaeroX** [iamludal/action-purge-workflow-runs#5]
secrets.GITHUB_TOKEN doesn't works, its but it works with an generated token: https://github.com/settings/tokens

may u could write that into die readme?

**Comment by iamfj** [comment]
Hi @SphaeroX,

It sounds like you're facing a configuration issue with this Action, where the default `secrets.GITHUB_TOKEN` isn't functioning as expected, but a Personal Access Token (PAT) works. Normally, `GITHUB_TOKEN` should suffice for most actions, as it is automatically generated by GitHub and has permissions aligned with the triggering user.

Could you provide more details about the error encountered during the failed runs? This could help in diagnosing the issue more accurately. Also, if your project is open source, could you share the repository link? This would allow me to look at your workflow configuration and potentially spot any misconfigurations.

Remember, the scope and permissions of `GITHUB_TOKEN` and a PAT can differ, which might be why you're seeing different behaviors. It's also possible that the action you're using requires permissions that `GITHUB_TOKEN` does not provide by default.

Looking forward to your response to assist you further.

**Comment by SphaeroX** [comment]
the repo is private but here is the log:

```
Run iamludal/action-purge-workflow-runs@v[2](https://github.com/SphaeroX/xxx/actions/runs/7444543574/job/20251126634#step:2:2)
  with:
    days-old: [3](https://github.com/xxx/murmli/actions/runs/7444543574/job/20251126634#step:2:3)0
    ignore-open-pull-requests: true
  env:
    GITHUB_TOKEN: ***
Searching for runs older than 30 days (before Sat, 09 Dec 2023 07:[4](https://github.com/SphaeroX/xxx/actions/runs/7444543574/job/20251126634#step:2:4)7:3[6](https://github.com/SphaeroX/xxx/actions/runs/7444543574/job/20251126634#step:2:6) GMT)
Error: Action failed with error: HttpError: Resource not accessible by integration
```

I'm not as familiar with GitHub like a pro, but the repo has been initialized by default.

**Comment by iamfj** [comment]
Thank you for sharing the log from your private repository. The error you're encountering, `HttpError: Resource not accessible by integration` typically occurs when the `GITHUB_TOKEN` used in a GitHub Action doesn't have sufficient permissions to access certain resources or perform specific actions.

Regarding your workflow, could you please share the `.yml` file of your workflow definition? This will help in understanding how the action is configured and whether there are any issues in the setup. You can redact any sensitive information before sharing.

Also, it would be helpful to check the configuration of the `GITHUB_TOKEN` in your repository settings. Here's how you can do that:

1. Go to your repository on GitHub.
2. Click on "Settings" and then navigate to "Actions" and click "General" in the sidebar.
4. Under "Actions permissions," ensure that the `GITHUB_TOKEN` settings are correctly set. This section controls the permissions for the `GITHUB_TOKEN` used in Actions.

![image](https://github.com/iamludal/action-purge-workflow-runs/assets/24557998/f0b473a7-6c4f-4671-b051-df7ec238e77d)

To give you a clearer idea, here's a placeholder for a typical workflow definition:

```yaml
name: Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 

jobs:
  maintenance:
    name: Maintenance
    runs-on: ubuntu-latest
      
    steps:
      - name: Delete old workflow runs
        uses: iamludal/action-purge-workflow-runs@v2
        with:
          days-old: 30
          ignore-open-pull-requests: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

In this example, the `GITHUB_TOKEN` is used to authenticate in a workflow. Your actual workflow might be more complex, but the usage of `GITHUB_TOKEN` should be somewhat similar.

Once you provide the workflow file, i can further diagnose the issue and suggest a solution.
